title: KOR How To Ask Questions The Smart Way
description: A Korean translated version of the article "How To Ask Questions The Smart Way"
theme: just-the-docs

url: https://wbjeon2k.github.io/how_to_ask_questions_the_smart_way_KOR 

aux_links:
  Template Repository: https://github.com/wbjeon2k/how_to_ask_questions_the_smart_way_KOR
