title: KOR How To Ask Questions The Smart Way
description: A Korean translation of the article "How To Ask Questions The Smart Way"
theme: just-the-docs

url: https://wbjeon2k.github.io/RTFM_KOR

aux_links:
  Template Repository: https://github.com/wbjeon2k/RTFM_KOR
